// JWT_SECRET is a Wrangler secret – not auto-generated by `wrangler types`
declare namespace Cloudflare {
	interface Env {
		JWT_SECRET: string;
	}
}

// App.Locals – augment with user session (adapter's Runtime is merged via @astrojs/cloudflare/types.d.ts)
declare namespace App {
	interface Locals {
		user?: {
			id: number;
			email: string;
		};
	}
}
